export const bachilleratoStudents = {
  "Sexto A": [
    "Bahamon Leon, Luciana",
    "Camargo Restrepo, Azul Helena",
    "Carmona Vasquez, Ana Sofia",
    "Corredor Vega, Mariana",
    "Cubillos Grosso, Juan Andres",
    "Diaz Alba, Juan Andres",
    "Echavarria Rodriguez, Jeronimo",
    "Espinosa Baron, Nicolas",
    "Garzon Diaz, Maria Camila",
    "Hernandez Huertas, Gabriela",
    "Malagon Osorio, Catalina",
    "Marin Gutierrez, Mariana",
    "Mongui Maldonado, Ana Sofia",
    "Moreno Lara, Mariana",
    "Morishita Kassem, Daigo",
    "Olivares Calderon, Pedro Rodolfo",
    "Ospina Moreno, Emilio",
    "Perez Cruz, Valeria",
    "Perez Valderrama, Ester Juanita",
    "Ramirez Jaramillo, Nicolas",
    "Rativa Lamus, Ana Sofia",
    "Reina Muniz, Isabella",
    "Rozo Mendoza, Samuel",
    "Silva Sanchez, Maria Fernanda",
    "Torres Alvarado, Juan Martin"
  ],
  "Séptimo A": [
    "Cadena Salazar, Samantha",
    "Chaves Solano, Isabella",
    "Devia Hernandez, Lorianne",
    "Fonseca Cruz, Maria Fernanda",
    "Garzon Diaz, Isabella",
    "Huerta Canon, Gabriel Moises",
    "Madden Medina, Emily Ann",
    "Madden Medina, Evan Francis",
    "Marquez Galan, Samuel Andres",
    "Olaya Ramirez, Nicolas",
    "Pena Beltran, Antonia",
    "Quitian Velasquez, Juan Diego",
    "Riano Carreño, Ellen Juliana",
    "Rojas Mendivelso, Ana Sofia",
    "Tarazona Grimaldo, Daniel Andres",
    "Trujillo Velasquez, Maria Alejandra",
    "Vanegas Santos, Ana Carolina",
    "Velez Cardenas, Sebastian"
  ],
  "Octavo A": [
    "Castro Rojas, Daniel",
    "Combariza Martinez, Mariana",
    "Gomez Celis, Santiago Andres",
    "Gonzalez Campos, Thomas",
    "Leguizamo Cardenas, Eva",
    "Munoz Rodriguez, Samuel Gustavo",
    "Orozco Castro, Maria Paz",
    "Pacheco Rodriguez, Maria Jose",
    "Pulido Alaix, Bianca Lucianna",
    "Quizobony Suarez, Andrea Sofia",
    "Rodriguez Bustos, Katherin Natalia",
    "Rodriguez Salamanca, Maria Jose",
    "Rozo Cucaita, Alejandro",
    "Rozo Urrego, Sebastian",
    "Salazar Sharp, Luz Mariana",
    "Trujillo Velasquez, Nicolas David"
  ],
  "Noveno A": [
    "Arzayus Arciniegas, Juan Fernando",
    "Bitar Guzman, Eileen Nicole",
    "Caicedo Quimbayo, Sara",
    "De Leon Forero, Maria Angelica",
    "Figueredo Prieto, Maria Paula",
    "Garcia Cuervo, Juan Andres",
    "Huerta Canon, Madeleine",
    "Lemus Beltran, Nicolle Sofia",
    "Lopez Arango, Shamil Esteban",
    "Martinez Moya, Emmanuel Alejandro",
    "Medina Carvajal, Felix Santiago",
    "Morales Tabares, Sebastian Leonardo",
    "Ospina Moreno, Alejandra",
    "Plata Loaiza, Matias",
    "Santos Oyola, Luz Gabriela",
    "Siado Leon, Benjamin",
    "Suarez Gonzalez, Carlos Federico",
    "Uriza Pena, Sarah",
    "Zapata Sanchez, Valentina"
  ],
  "Décimo A": [
    "Alarcon Torres, Maria Sofia",
    "Castro Caro, Isabella",
    "Contreras Urbano, Jacobo",
    "Gomez Benavides, Mariana",
    "Lancheros Herrera, Jeremy",
    "Leguizamon Osorio, Jesus David",
    "Mendieta Escobar, Juan Sebastian",
    "Ortiz Carvajal, Juan Pablo",
    "Ossa Zuluaga, Samuel",
    "Riano Carreño, Juan Jose",
    "Rueda Quiroga, Silvana Lucia",
    "Ruiz Forero, David Felipe",
    "Toro Arrieta, Juan Jose",
    "Valdivieso Marin, Daniel Arturo"
  ],
  "Undécimo A": [
    "Acuna Perez, Sara Sofia",
    "Cuta Alfonso, Jose Cristobal",
    "Devis Rivera, Salome",
    "Diaz Cardenas, Ana Gabriela",
    "Galindo Acosta, Luciana",
    "Gonzalez Valderrama, Samuel Felipe",
    "Hernandez Mora, Juan Andres",
    "Ibanez Gomez, Samuel David",
    "Manrique Villarraga, Angel Santiago",
    "Morales Tabares, Juliana Andrea",
    "Moreno Osorio, Mateo",
    "Nunez Lopez, Thomas",
    "Posada Cubides, Carlos Gustavo",
    "Posada Cubides, Gabriel Eduardo",
    "Ramos Castillo, Izabella",
    "Reyes Ortiz, Emily Salome",
    "Rojas Torres, Damian",
    "Romero Villamil, Gabriela",
    "Zambrano Parra, Sofia"
  ]
};
